//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JudgeBot.Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Presentation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Presentation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JudgeBot.Presentation.Resources.Presentation", typeof(Presentation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует.
        /// </summary>
        internal static string Absent {
            get {
                return ResourceManager.GetString("Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обвинитель 🫵.
        /// </summary>
        internal static string AccuserBtnLbl {
            get {
                return ResourceManager.GetString("AccuserBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дело не было сохранено.
        /// </summary>
        internal static string ActDoesNotCreated {
            get {
                return ResourceManager.GetString("ActDoesNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дело не было сохранено вследствие ошибки: {0}.
        /// </summary>
        internal static string ActDoesNotCreatedException {
            get {
                return ResourceManager.GetString("ActDoesNotCreatedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Твой список дел в роли обвиняемого:.
        /// </summary>
        internal static string ActListDefendantDescription {
            get {
                return ResourceManager.GetString("ActListDefendantDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дело успешно создано! 
        ///ID дела: {0}.
        /// </summary>
        internal static string ActSuccessfullyCreated {
            get {
                return ResourceManager.GetString("ActSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад ⬅️.
        /// </summary>
        internal static string BackBtnLbl {
            get {
                return ResourceManager.GetString("BackBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обвиняемый 🥷.
        /// </summary>
        internal static string DefendantBtnLbl {
            get {
                return ResourceManager.GetString("DefendantBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английский 🇺🇸.
        /// </summary>
        internal static string EnglishBtnLbl {
            get {
                return ResourceManager.GetString("EnglishBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь❓.
        /// </summary>
        internal static string HelpCommandBtnLbl {
            get {
                return ResourceManager.GetString("HelpCommandBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет. Это JudgeBot - бот для судов и наказаний.
        ///
        ///Здесь ты можешь создать дело против того, кто тебе насолил.
        ///Здесь ты можешь смотреть дела против себя и многое другое!
        ///
        ///Если хочешь создать новое дело, то просто тегни меня к сообщению нужного пользователя..
        /// </summary>
        internal static string HelpCommandDescription {
            get {
                return ResourceManager.GetString("HelpCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверное описание дела.
        /// </summary>
        internal static string InvalidActDescription {
            get {
                return ResourceManager.GetString("InvalidActDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверное название дела.
        /// </summary>
        internal static string InvalidActName {
            get {
                return ResourceManager.GetString("InvalidActName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная команда.
        /// </summary>
        internal static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Присяжный 🗣.
        /// </summary>
        internal static string JuryBtnLbl {
            get {
                return ResourceManager.GetString("JuryBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string LanguageBtnLbl {
            get {
                return ResourceManager.GetString("LanguageBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите язык.
        /// </summary>
        internal static string LanguageMenuDescription {
            get {
                return ResourceManager.GetString("LanguageMenuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Судья ⚖️.
        /// </summary>
        internal static string MagistrateBtnLbl {
            get {
                return ResourceManager.GetString("MagistrateBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список судей.
        /// </summary>
        internal static string MagistrateList {
            get {
                return ResourceManager.GetString("MagistrateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои дела.
        /// </summary>
        internal static string MyActs {
            get {
                return ResourceManager.GetString("MyActs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать твои дела в роли....
        /// </summary>
        internal static string MyActsMenuDescription {
            get {
                return ResourceManager.GetString("MyActsMenuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите создание дела.
        /// </summary>
        internal static string NewActSceneSetActApproveAct {
            get {
                return ResourceManager.GetString("NewActSceneSetActApproveAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введи описание дела.
        /// </summary>
        internal static string NewActSceneSetActDescription {
            get {
                return ResourceManager.GetString("NewActSceneSetActDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введи название дела.
        /// </summary>
        internal static string NewActSceneSetActName {
            get {
                return ResourceManager.GetString("NewActSceneSetActName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто жертва? Выбери или тегни.
        /// </summary>
        internal static string NewActSceneSetActVictim {
            get {
                return ResourceManager.GetString("NewActSceneSetActVictim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ну нет.. блятб тегни.
        /// </summary>
        internal static string NewActSceneSetActVictimInvalidMention {
            get {
                return ResourceManager.GetString("NewActSceneSetActVictimInvalidMention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я жертва.
        /// </summary>
        internal static string NewActSceneSetActVictimIsMe {
            get {
                return ResourceManager.GetString("NewActSceneSetActVictimIsMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Никто.
        /// </summary>
        internal static string NewActSceneSetActVictimIsNobody {
            get {
                return ResourceManager.GetString("NewActSceneSetActVictimIsNobody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский 🇷🇺.
        /// </summary>
        internal static string RussianBtnLbl {
            get {
                return ResourceManager.GetString("RussianBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки ⚙️.
        /// </summary>
        internal static string SettingsMenuBtnLbl {
            get {
                return ResourceManager.GetString("SettingsMenuBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string SettingsMenuDescription {
            get {
                return ResourceManager.GetString("SettingsMenuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет, {0}. Посадим сегодня кого-нибудь?.
        /// </summary>
        internal static string StartMenuDescription {
            get {
                return ResourceManager.GetString("StartMenuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жертва 🧖.
        /// </summary>
        internal static string VictimBtnLbl {
            get {
                return ResourceManager.GetString("VictimBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будет распределен.
        /// </summary>
        internal static string WillBeAssigned {
            get {
                return ResourceManager.GetString("WillBeAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
