services:
  db:
    image: postgres:15.3
    container_name: judge_bot
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/judge_init_db.sh
  judgebot:
    image: judgebot
    build:
      context: .
      dockerfile: JudgeBot/Dockerfile
  garnet:
    image: 'ghcr.io/microsoft/garnet'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - garnetdata:/data

volumes:
  garnetdata:
  database_data: